"use client";
import {useEffect,useRef} from 'react';
import type {BufferGeometry,Material,Texture} from 'three';
export default function ArchiveProp({opened,onOpen}:{opened:boolean;onOpen:()=>void}){
 const host=useRef<HTMLDivElement>(null),isOpen=useRef(opened),callback=useRef(onOpen),rotate=useRef((_:number)=>{}),reset=useRef(()=>{});isOpen.current=opened;callback.current=onOpen;
 useEffect(()=>{let cancelled=false,cleanup=()=>{};import('three').then(T=>{if(cancelled||!host.current)return;const el=host.current,scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,100);camera.position.set(0,.25,7.8);const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);scene.add(new T.AmbientLight(0xffedda,2));const lamp=new T.DirectionalLight(0xffe3b5,3);lamp.position.set(-3,5,5);scene.add(lamp);const fill=new T.DirectionalLight(0xadc1e0,1.3);fill.position.set(4,0,-4);scene.add(fill);
 const group=new T.Group();group.rotation.set(-.07,-.22,-.04);scene.add(group);const geometries:BufferGeometry[]=[];const materials:Material[]=[];const textures:Texture[]=[];
 const box=(w:number,h:number,d:number,color:number)=>{const g=new T.BoxGeometry(w,h,d),m=new T.MeshStandardMaterial({color,roughness:.9});geometries.push(g);materials.push(m);return new T.Mesh(g,m)};
 const back=box(3.3,2.35,.045,0xae8960);back.position.z=-.1;group.add(back);const front=box(3.3,1.98,.045,0xc5a376);front.position.set(0,-.185,.13);group.add(front);
 for(const x of [-1.63,1.63]){const side=box(.055,2.35,.23,0x987450);side.position.set(x,0,.01);group.add(side)}const bottom=box(3.3,.06,.23,0x987450);bottom.position.y=-1.17;group.add(bottom);
 const label=document.createElement('canvas');label.width=1024;label.height=512;const ctx=label.getContext('2d')!;ctx.fillStyle='#d7bc90';ctx.fillRect(0,0,1024,512);ctx.fillStyle='#59452f';ctx.font='24px monospace';ctx.fillText('PERSONAL ARCHIVE / 02',65,90);ctx.font='bold 76px Microsoft YaHei';ctx.fillText('段静怡 · 个人档案',65,245);ctx.font='28px monospace';ctx.fillText('LIFE, MOMENTS & LITTLE STORIES',65,345);ctx.strokeStyle='#8e714e';ctx.strokeRect(35,35,954,442);const texture=new T.CanvasTexture(label);texture.colorSpace=T.SRGBColorSpace;textures.push(texture);const lg=new T.PlaneGeometry(2.65,1.32),lm=new T.MeshBasicMaterial({map:texture});geometries.push(lg);materials.push(lm);const labelMesh=new T.Mesh(lg,lm);labelMesh.position.set(0,-.15,.159);group.add(labelMesh);
 const flapPivot=new T.Group();flapPivot.position.set(0,1.15,-.1);const flap=box(3.29,.84,.035,0xb69266);flap.position.set(0,-.4,.24);flapPivot.add(flap);group.add(flapPivot);
 const loader=new T.TextureLoader();const photos=Array.from({length:6},(_,i)=>{const t=loader.load(`/dossier/life-${i}.webp`);t.colorSpace=T.SRGBColorSpace;textures.push(t);const g=new T.PlaneGeometry(.88,1.08),m=new T.MeshBasicMaterial({map:t,side:T.DoubleSide});geometries.push(g);materials.push(m);const photo=new T.Mesh(g,m);photo.position.set((i-2.5)*.12,.1,-.04+i*.014);group.add(photo);return photo});
 let progress=0,down=false,moved=0,x=0,y=0;renderer.domElement.onpointerdown=e=>{down=true;moved=0;x=e.clientX;y=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(!down)return;const dx=e.clientX-x,dy=e.clientY-y;moved+=Math.abs(dx)+Math.abs(dy);group.rotation.y+=dx*.012;group.rotation.x=Math.max(-.65,Math.min(.65,group.rotation.x+dy*.006));x=e.clientX;y=e.clientY};renderer.domElement.onpointerup=()=>{if(down&&moved<6)callback.current();down=false};renderer.domElement.onpointercancel=()=>{down=false};rotate.current=delta=>group.rotation.y+=delta;reset.current=()=>group.rotation.set(-.07,-.22,-.04);
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;const draw=()=>{const target=isOpen.current?1:0;progress=reduced?target:progress+(target-progress)*.09;flapPivot.rotation.x=-progress*2.65;photos.forEach((p,i)=>{p.position.y=.1+progress*(1.48+Math.sin(i)*.16);p.position.x=(i-2.5)*(.12+progress*.28);p.rotation.z=(i-2.5)*-.07*progress;p.position.z=-.04+i*.014});renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();cleanup=()=>{cancelAnimationFrame(frame);observer.disconnect();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()};}).catch(()=>{});return()=>{cancelled=true;cleanup()};},[]);
 return <div className="archive-object"><div ref={host} className="archive-canvas" role="img" aria-label="可拖动360度旋转的个人档案袋，点击打开"/><p>拖动旋转 360° · 点击袋子{opened?'收起':'打开'}</p><div className="archive-model-controls"><button aria-label="向左旋转档案袋" onClick={()=>rotate.current(-.5)}>↶</button><button onClick={()=>reset.current()}>回正</button><button aria-label="向右旋转档案袋" onClick={()=>rotate.current(.5)}>↷</button><button onClick={onOpen}>{opened?'收起档案袋':'打开档案袋'}</button></div></div>
}
