"use client";
import {useEffect,useRef} from 'react';

export default function ArchiveNotebook({onReady,skip=false}:{onReady:()=>void;skip?:boolean}){
 const host=useRef<HTMLDivElement>(null),ready=useRef(onReady),skipRef=useRef(skip);
 ready.current=onReady;skipRef.current=skip;
 useEffect(()=>{let stopped=false,dispose=()=>{};import('three').then(T=>{
  if(stopped||!host.current)return;
  const el=host.current,scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,50);camera.position.set(0,0,9.3);
  const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;el.appendChild(renderer.domElement);
  scene.add(new T.HemisphereLight(0xfffbf2,0xb7c4cf,2.6));const key=new T.DirectionalLight(0xfff1dd,3.2);key.position.set(-3,4,7);key.castShadow=true;scene.add(key);const rim=new T.DirectionalLight(0xbfd4ee,1.2);rim.position.set(4,-2,5);scene.add(rim);
  const geometries:InstanceType<typeof T.BufferGeometry>[]=[],materials:InstanceType<typeof T.Material>[]=[],textures:InstanceType<typeof T.Texture>[]=[];
  const coverTexture=new T.TextureLoader().load('/dossier/book-journal-cover.png');coverTexture.colorSpace=T.SRGBColorSpace;textures.push(coverTexture);
  const cloth=new T.MeshStandardMaterial({color:0x9a5834,roughness:.94}),paper=new T.MeshStandardMaterial({color:0xfff3d2,roughness:1,side:T.DoubleSide});materials.push(cloth,paper);
  const rounded=(w:number,h:number,r:number,d:number,material:InstanceType<typeof T.Material>)=>{const s=new T.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);const g=new T.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,bevelSize:.025,bevelThickness:.025});g.translate(0,0,-d/2);geometries.push(g);const m=new T.Mesh(g,material);m.castShadow=true;m.receiveShadow=true;return m};
  const box=(w:number,h:number,d:number,material:InstanceType<typeof T.Material>)=>{const g=new T.BoxGeometry(w,h,d),m=new T.Mesh(g,material);geometries.push(g);m.castShadow=true;m.receiveShadow=true;return m};
  const book=new T.Group();scene.add(book);const stack=rounded(2.34,3.08,.1,.28,paper);stack.position.z=-.02;book.add(stack);const back=rounded(2.52,3.3,.16,.1,cloth);back.position.z=-.2;book.add(back);const spine=box(.16,3.12,.42,cloth);spine.position.set(-1.2,0,-.02);book.add(spine);
  const coverPivot=new T.Group();coverPivot.position.set(-1.26,0,.2);book.add(coverPivot);const coverBase=rounded(2.52,3.3,.16,.1,cloth);coverBase.position.x=1.26;coverPivot.add(coverBase);const artG=new T.PlaneGeometry(2.72,3.48),artM=new T.MeshStandardMaterial({map:coverTexture,transparent:true,alphaTest:.03,roughness:.92});geometries.push(artG);materials.push(artM);const art=new T.Mesh(artG,artM);art.position.set(1.2,0,.078);coverPivot.add(art);
  const leaves=Array.from({length:7},(_,i)=>{const pivot=new T.Group();pivot.position.set(-1.16,0,.16-i*.014);const g=new T.PlaneGeometry(2.32,3.02,38,12),positions=g.attributes.position;if(positions instanceof T.BufferAttribute)positions.setUsage(T.DynamicDrawUsage);const base=new Float32Array(positions.array as ArrayLike<number>);g.computeVertexNormals();geometries.push(g);const pagePaper=paper.clone();pagePaper.color.offsetHSL(0,0,-i*.012);materials.push(pagePaper);const page=new T.Mesh(g,pagePaper);page.position.x=1.16;page.castShadow=true;page.receiveShadow=true;pivot.add(page);book.add(pivot);return{pivot,page,positions,base,index:i}});
  let drag=false,last=0,yaw=0,frame=0,announced=false;renderer.domElement.onpointerdown=e=>{drag=true;last=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(drag){yaw+=(e.clientX-last)*.012;last=e.clientX}};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>{drag=false};const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight,false)};const observer=new ResizeObserver(resize);observer.observe(el);resize();const start=performance.now(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const ease=(v:number)=>{const p=Math.max(0,Math.min(1,v));return 1-Math.pow(1-p,3)};
  const draw=()=>{const t=reduced||skipRef.current?4:(performance.now()-start)/1000,settle=ease((t-.3)/.4),opened=ease((t-.62)/.52);book.rotation.set(-settle*.11,yaw-.055,Math.PI/2*settle);book.position.set(0,-.12*settle,0);book.scale.setScalar(1+settle*.12);coverPivot.rotation.y=-(Math.PI-.055)*opened-Math.sin(opened*Math.PI)*.08;stack.visible=opened<.93;leaves.forEach((leaf,i)=>{const flip=ease((t-.78-i*.09)/.58),lift=Math.sin(flip*Math.PI),target=-(.55+i*.08);leaf.pivot.rotation.y=target*flip-lift*.72;leaf.pivot.rotation.z=Math.sin(flip*Math.PI)*(.018+(i%3)*.004);leaf.pivot.position.x=-1.16+flip*i*.22;leaf.pivot.position.z=.16-i*.014+flip*i*.006;const pos=leaf.positions;for(let v=0;v<pos.count;v++){const o=v*3,bx=leaf.base[o],by=leaf.base[o+1],u=(bx+1.16)/2.32,hinge=Math.sin(Math.PI*u),edge=u*u,travel=lift*(.42*hinge+.12*edge),ripple=lift*.035*Math.sin(u*Math.PI*2+i*.7),breathe=flip>.98?Math.sin(t*1.55+i*.8+u*3.2)*.013*hinge:0,settledCurl=flip*(.028+i*.0025)*hinge;pos.setXYZ(v,bx,by+ripple,travel+settledCurl+breathe)}pos.needsUpdate=true;leaf.page.geometry.computeVertexNormals()});if(t>1.95&&!announced){announced=true;ready.current()}renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();
  dispose=()=>{cancelAnimationFrame(frame);observer.disconnect();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()};
 }).catch(()=>{if(!stopped)ready.current()});return()=>{stopped=true;dispose()};},[]);
 return <div className="notebook-stage" ref={host} role="img" aria-label="柔软的个人档案手账本，自动翻页，拖动可以360度旋转"/>;
}
